fix: use `cargo build` for compilation when emulating `cargo run`
Given the following binary generated by `cargo new --bin`:

```
// src/main.rs
fn main() {
    println!("Hello, world!");
}
```

Running `cargo debug run` panics due to invalid JSON; cargo-debug assumes that
the supplied subcommand is either `test` or `build` but does not validate this,
and then assumes that the supplied subcommand only emits JSON formatted manifest
information on stdout. The above example that writes to stdout breaks that assumption,
causing a panic.

```
 cargo debug run
   Compiling example v0.1.0 (/Users/user/personal/projects/example)
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `target/debug/example`
thread 'main' panicked at src/main.rs:131:23:
Invalid cargo JSON message: Error("expected value", line: 3, column: 1)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This commit resolves this by adding the following:

1. proper adaptation for `cargo-debug run` similar to the special-casing for `cargo-debug test`
2. checks that will warn users if the subcommand isn't known (and may fail)
3. error handling when an invalid cargo metadata message is received (replacing a panic with a graceful exit)